#ifndef QUTAG_MC_TIMETAG_PLUGIN_GLOBAL_H
#define QUTAG_MC_TIMETAG_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUTAG_MC_TIMETAG_PLUGIN_LIBRARY)
#  define QUTAG_MC_TIMETAG_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QUTAG_MC_TIMETAG_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QUTAG_MC_TIMETAG_PLUGIN_GLOBAL_H
